-- Marketing drafts: posts generated by the marketing agent, pending review and publish
create table if not exists marketing_drafts (
  id uuid primary key default gen_random_uuid(),
  topic text not null,
  caption text not null,
  image_prompt text,
  image_url text,
  platforms text[] default array['instagram', 'facebook'],
  status text not null default 'pending_approval',
  approval_token text unique,
  published_results jsonb,
  created_at timestamptz not null default now(),
  approved_at timestamptz,
  published_at timestamptz,
  published_by text
);

create index if not exists idx_marketing_drafts_status on marketing_drafts(status);
create index if not exists idx_marketing_drafts_created on marketing_drafts(created_at desc);

-- Enable Row Level Security (service role bypasses this; this is a safety default)
alter table marketing_drafts enable row level security;

-- Storage bucket for generated images (public read)
insert into storage.buckets (id, name, public)
values ('marketing-images', 'marketing-images', true)
on conflict (id) do nothing;
